name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Test
      run: make test

    # Note:
    # Test is executed in two times.
    # There should be a better way.
    #
    # Ref: https://github.com/codecov/example-swift
    - name: Test for coverage
      run: |
        xcodebuild \
          -scheme SwiftPrettyPrint-Package \
          -project SwiftPrettyPrint.xcodeproj \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 11' \
          test

    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          bundler-${{ hashFiles('Gemfile.lock') }}

    - name: Bundle install
      run: |
        bundle

    - name: Run Integration Test
      run: |
        make integration-test
